---
title: Bellroute's devlog
url: "https://bellroute.github.io"
baseurl: ""
desc: A minimal blog for off-topic blog entries.
about: I am back-end developer
image: https://drive.google.com/open?id=1IIwQ1Hamo9day6oHszwIkvfca6S8eorM
excerpt_separator: "<!-- more -->"
markdown: kramdown
gems:
- jekyll-paginate
exclude:
  - .jekyll-metadata
  - README.md
  - CNAME
paginate: 5
paginate_path: "/:num/"
highlighter: rouge
permalink: pretty
